Metrics/LineLength:
  Max: 160

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Max: 100

Metrics/MethodLength:
  Max: 60

Style/MultilineTernaryOperator:
  Enabled: false

Lint/SuppressedException:
  Enabled: false
